version: 2
updates:
- package-ecosystem: pip
  # As this project is not currently active, disable Dependabot
  open-pull-requests-limit: 0
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "05:00"
    timezone: "America/Chicago"
