name: "CI Tests"

on:
  push:
    branches: [ main, develop ]
  pull_request:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: air-quality-bot-singleton-e2e-tests

jobs:
  ci:
    name: "CI Tests"

    env:
      AIR_QUALITY_BOT_PHONE_NUMBER: ${{ secrets.AIR_QUALITY_BOT_PHONE_NUMBER }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_E2E_FROM_PHONE_NUMBER: ${{ secrets.TWILIO_E2E_FROM_PHONE_NUMBER }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run:
          make install
      - name: Run tests
        run:
          make test

  automerge:
    name: "Auto Approve"
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          use-github-auto-merge: true
